name: contacts_service_example
description: Demonstrates how to use the contacts_service plugin.
publish_to: 'none'
version: 0.0.1


environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.1"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  collection: any
  intl: any

  permission_handler: ^11.3.1

  contacts_service:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
