name: contacts_service
description: A Flutter plugin to retrieve and manage contacts on Android and iOS devices.
version: 0.7.0
homepage: https://github.com/lukasgit/flutter_contacts
maintainer: Lukas Dickie (@lukasgit), Anton Ustinoff (a.a.ustinoff@gmail.com)

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter

  # Utilities
  collection: any
  meta: any

dev_dependencies:
  # Integration tests for Flutter
  integration_test:
    sdk: flutter
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: flutter.plugins.contactsservice.contactsservice
        pluginClass: ContactsServicePlugin
      ios:
        pluginClass: ContactsServicePlugin
